// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: hayasaka/kaguya/user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCUserClient is the client API for GRPCUser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCUserClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type gRPCUserClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCUserClient(cc grpc.ClientConnInterface) GRPCUserClient {
	return &gRPCUserClient{cc}
}

func (c *gRPCUserClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/user.GRPCUser/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCUserServer is the server API for GRPCUser service.
// All implementations must embed UnimplementedGRPCUserServer
// for forward compatibility
type GRPCUserServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	mustEmbedUnimplementedGRPCUserServer()
}

// UnimplementedGRPCUserServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCUserServer struct {
}

func (UnimplementedGRPCUserServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGRPCUserServer) mustEmbedUnimplementedGRPCUserServer() {}

// UnsafeGRPCUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCUserServer will
// result in compilation errors.
type UnsafeGRPCUserServer interface {
	mustEmbedUnimplementedGRPCUserServer()
}

func RegisterGRPCUserServer(s grpc.ServiceRegistrar, srv GRPCUserServer) {
	s.RegisterService(&GRPCUser_ServiceDesc, srv)
}

func _GRPCUser_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCUserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.GRPCUser/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCUserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCUser_ServiceDesc is the grpc.ServiceDesc for GRPCUser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCUser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.GRPCUser",
	HandlerType: (*GRPCUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GRPCUser_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hayasaka/kaguya/user.proto",
}
