// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: hayasaka/kaguya/auth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GRPCAuthClient is the client API for GRPCAuth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GRPCAuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
}

type gRPCAuthClient struct {
	cc grpc.ClientConnInterface
}

func NewGRPCAuthClient(cc grpc.ClientConnInterface) GRPCAuthClient {
	return &gRPCAuthClient{cc}
}

func (c *gRPCAuthClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/auth.GRPCAuth/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gRPCAuthClient) Session(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, "/auth.GRPCAuth/Session", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GRPCAuthServer is the server API for GRPCAuth service.
// All implementations must embed UnimplementedGRPCAuthServer
// for forward compatibility
type GRPCAuthServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Session(context.Context, *SessionRequest) (*SessionResponse, error)
	mustEmbedUnimplementedGRPCAuthServer()
}

// UnimplementedGRPCAuthServer must be embedded to have forward compatible implementations.
type UnimplementedGRPCAuthServer struct {
}

func (UnimplementedGRPCAuthServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGRPCAuthServer) Session(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedGRPCAuthServer) mustEmbedUnimplementedGRPCAuthServer() {}

// UnsafeGRPCAuthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GRPCAuthServer will
// result in compilation errors.
type UnsafeGRPCAuthServer interface {
	mustEmbedUnimplementedGRPCAuthServer()
}

func RegisterGRPCAuthServer(s grpc.ServiceRegistrar, srv GRPCAuthServer) {
	s.RegisterService(&GRPCAuth_ServiceDesc, srv)
}

func _GRPCAuth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCAuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.GRPCAuth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCAuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GRPCAuth_Session_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GRPCAuthServer).Session(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.GRPCAuth/Session",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GRPCAuthServer).Session(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GRPCAuth_ServiceDesc is the grpc.ServiceDesc for GRPCAuth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GRPCAuth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.GRPCAuth",
	HandlerType: (*GRPCAuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _GRPCAuth_Login_Handler,
		},
		{
			MethodName: "Session",
			Handler:    _GRPCAuth_Session_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hayasaka/kaguya/auth.proto",
}
